version: '3.7'

services:
  ingress:
    image: haproxy:2.3
    restart: on-failure
    ports:
      - 127.0.0.1:443:443
    volumes:
      - type: bind
        source: ./ingress/conf
        target: /usr/local/etc/haproxy
        read_only: true
    networks:
      internet:
        ipv4_address: 172.10.0.2


  dic-fhir-proxy:
    image: ghcr.io/highmed/fhir_proxy:0.5.0-M2
    restart: on-failure
    volumes:
      - type: bind
        source: ./dic/fhir/proxy/ssl
        target: /usr/local/apache2/ssl
    environment:
      HTTPS_SERVER_NAME_PORT: dic:443
      APP_SERVER_IP: dic-fhir-app
    networks:
      internet:
        ipv4_address: 172.10.0.3
        aliases:
          - dic
      dic-fhir-frontend:
    depends_on:
      - ingress
      - dic-fhir-app
  dic-fhir-app:
    image: ghcr.io/highmed/fhir:0.5.0-M2
    restart: on-failure
    volumes:
      - type: bind
        source: ./dic/fhir/app/conf
        target: /opt/fhir/conf
      - type: bind
        source: ./dic/fhir/app/log
        target: /opt/fhir/log
    environment:
      TZ: Europe/Berlin
    networks:
      - dic-fhir-frontend
      - dic-fhir-backend
    depends_on:
      - dic-fhir-db
  dic-fhir-db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d fhir" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/dic-fhir-postgres_password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: fhir
    networks:
      - dic-fhir-backend
    volumes:
      - type: volume
        source: dic-fhir-db-data
        target: /var/lib/postgresql/data
    secrets:
      - dic-fhir-postgres_password

  # dic-bpe-proxy not needed
  dic-bpe-app:
    image: ghcr.io/highmed/bpe:0.5.0-M2
    restart: on-failure
    ports:
      - 127.0.0.1:5003:5003
    volumes:
      - type: bind
        source: ./dic/bpe/app/conf
        target: /opt/bpe/conf
        read_only: true
      - type: bind
        source: ./dic/bpe/app/plugin
        target: /opt/bpe/plugin
        read_only: true
      - type: bind
        source: ./dic/bpe/app/process
        target: /opt/bpe/process
        read_only: true
      - type: bind
        source: ./dic/bpe/app/log
        target: /opt/bpe/log
      - type: bind
        source: ./dic/bpe/app/last_event
        target: /opt/bpe/last_event
    environment:
      TZ: Europe/Berlin
      EXTRA_JVM_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5003
    networks:
      dic-bpe-frontend:
      dic-bpe-backend:
      internet:
        ipv4_address: 172.10.0.103
    depends_on:
      - dic-bpe-db
      - dic-fhir-proxy
    # - dic-fhir-store not defining a dependency here, dic-fhir-store* needs to be started manually
  dic-bpe-db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d bpe" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/dic-bpe-postgres_password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: bpe
    networks:
      - dic-bpe-backend
    volumes:
      - type: volume
        source: dic-bpe-db-data
        target: /var/lib/postgresql/data
    secrets:
      - dic-bpe-postgres_password
  dic-fhir-store-hapi:
    build: ./dic/hapi
    restart: on-failure
    ports:
      - 127.0.0.1:8080:8080
    environment:
      TZ: Europe/Berlin
    networks:
      dic-bpe-backend:
        aliases:
          - dic-fhir-store
  dic-fhir-store-blaze:
    image: ghcr.io/num-codex/blaze
    ports:
      - 127.0.0.1:8080:8080
    environment:
      TZ: Europe/Berlin
    networks:
      dic-bpe-backend:
        aliases:
          - dic-fhir-store


  gth-fhir-proxy:
    image: ghcr.io/highmed/fhir_proxy:0.5.0-M2
    restart: on-failure
    volumes:
      - type: bind
        source: ./gth/fhir/proxy/ssl
        target: /usr/local/apache2/ssl
    environment:
      HTTPS_SERVER_NAME_PORT: gth:443
      APP_SERVER_IP: gth-fhir-app
    networks:
      internet:
        ipv4_address: 172.10.0.4
        aliases:
          - gth
      gth-fhir-frontend:
    depends_on:
      - ingress
      - gth-fhir-app
  gth-fhir-app:
    image: ghcr.io/highmed/fhir:0.5.0-M2
    restart: on-failure
    volumes:
      - type: bind
        source: ./gth/fhir/app/conf
        target: /opt/fhir/conf
      - type: bind
        source: ./gth/fhir/app/log
        target: /opt/fhir/log
    environment:
      TZ: Europe/Berlin
    networks:
      - gth-fhir-frontend
      - gth-fhir-backend
    depends_on:
      - gth-fhir-db
  gth-fhir-db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d fhir" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/gth-fhir-postgres_password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: fhir
    networks:
      - gth-fhir-backend
    volumes:
      - type: volume
        source: gth-fhir-db-data
        target: /var/lib/postgresql/data
    secrets:
      - gth-fhir-postgres_password

  # gth-bpe-proxy not needed
  gth-bpe-app:
    image: ghcr.io/highmed/bpe:0.5.0-M2
    restart: on-failure
    ports:
      - 127.0.0.1:5004:5004
    volumes:
      - type: bind
        source: ./gth/bpe/app/conf
        target: /opt/bpe/conf
        read_only: true
      - type: bind
        source: ./gth/bpe/app/plugin
        target: /opt/bpe/plugin
        read_only: true
      - type: bind
        source: ./gth/bpe/app/process
        target: /opt/bpe/process
        read_only: true
      - type: bind
        source: ./gth/bpe/app/log
        target: /opt/bpe/log
      - type: bind
        source: ./gth/bpe/app/last_event
        target: /opt/bpe/last_event
    environment:
      TZ: Europe/Berlin
      EXTRA_JVM_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5004
    networks:
      gth-bpe-frontend:
      gth-bpe-backend:
      internet:
        ipv4_address: 172.10.0.104
    depends_on:
      - gth-bpe-db
      - gth-fhir-proxy
  gth-bpe-db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d bpe" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/gth-bpe-postgres_password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: bpe
    networks:
      - gth-bpe-backend
    volumes:
      - type: volume
        source: gth-bpe-db-data
        target: /var/lib/postgresql/data
    secrets:
      - gth-bpe-postgres_password


  crr-fhir-proxy:
    image: ghcr.io/highmed/fhir_proxy:0.5.0-M2
    restart: on-failure
    volumes:
      - type: bind
        source: ./crr/fhir/proxy/ssl
        target: /usr/local/apache2/ssl
    environment:
      HTTPS_SERVER_NAME_PORT: crr:443
      APP_SERVER_IP: crr-fhir-app
    networks:
      internet:
        ipv4_address: 172.10.0.5
        aliases:
          - crr
      crr-fhir-frontend:
    depends_on:
      - ingress
      - crr-fhir-app
  crr-fhir-app:
    image: ghcr.io/highmed/fhir:0.5.0-M2
    restart: on-failure
    volumes:
      - type: bind
        source: ./crr/fhir/app/conf
        target: /opt/fhir/conf
      - type: bind
        source: ./crr/fhir/app/log
        target: /opt/fhir/log
    environment:
      TZ: Europe/Berlin
    networks:
      - crr-fhir-frontend
      - crr-fhir-backend
    depends_on:
      - crr-fhir-db
  crr-fhir-db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d fhir" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/crr-fhir-postgres_password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: fhir
    networks:
      - crr-fhir-backend
    volumes:
      - type: volume
        source: crr-fhir-db-data
        target: /var/lib/postgresql/data
    secrets:
      - crr-fhir-postgres_password

  # crr-bpe-proxy not needed
  crr-bpe-app:
    image: ghcr.io/highmed/bpe:0.5.0-M2
    restart: on-failure
    ports:
      - 127.0.0.1:5005:5005
    volumes:
      - type: bind
        source: ./crr/bpe/app/conf
        target: /opt/bpe/conf
        read_only: true
      - type: bind
        source: ./crr/bpe/app/plugin
        target: /opt/bpe/plugin
        read_only: true
      - type: bind
        source: ./crr/bpe/app/process
        target: /opt/bpe/process
        read_only: true
      - type: bind
        source: ./crr/bpe/app/log
        target: /opt/bpe/log
      - type: bind
        source: ./crr/bpe/app/last_event
        target: /opt/bpe/last_event
    environment:
      TZ: Europe/Berlin
      EXTRA_JVM_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      crr-bpe-frontend:
      crr-bpe-backend:
      internet:
        ipv4_address: 172.10.0.105
    depends_on:
      - crr-bpe-db
      - crr-fhir-proxy
    # - crr-fhir-bridge not defining a dependency here, crr-fhir-bridge* needs to be started manually
  crr-bpe-db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d bpe" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/crr-bpe-postgres_password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: bpe
    networks:
      - crr-bpe-backend
    volumes:
      - type: volume
        source: crr-bpe-db-data
        target: /var/lib/postgresql/data
    secrets:
      - crr-bpe-postgres_password
  crr-ehrbase-db:
    image: ehrbase/ehrbase-postgres:latest
    networks:
      - crr-ehrbase-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER: ehrbase
      EHRBASE_PASSWORD: ehrbase
      TZ: Europe/Berlin
  crr-ehrbase:
    image: ehrbase/ehrbase:next
    networks:
      - crr-ehrbase-network
    environment:
      DB_URL: jdbc:postgresql://crr-ehrbase-db:5432/ehrbase
      DB_USER: ehrbase
      DB_PASS: ehrbase
      SECURITY_AUTHTYPE: BASIC
      SECURITY_AUTHUSER: myuser
      SECURITY_AUTHPASSWORD: myPassword432
      SECURITY_AUTHADMINUSER: myadmin
      SECURITY_AUTHADMINPASSWORD: mySuperAwesomePassword123
      SYSTEM_NAME: local.ehrbase.org
      ADMIN_API_ACTIVE: 'true'
      TZ: Europe/Berlin
    depends_on:
      - crr-ehrbase-db
  crr-fhir-bridge:
    image: ehrbase/fhir-bridge:1.2.1
    ports:
      - 127.0.0.1:8888:8888
      - 127.0.0.1:5006:5006
    networks:
      - crr-ehrbase-network
      - crr-bpe-backend
    environment:
      FHIR_BRIDGE_EHRBASE_BASE_URL: http://crr-ehrbase:8080/ehrbase/rest/openehr/v1/
      FHIR_BRIDGE_FHIR_VALIDATION_OPTIONAL_IDENTIFIER: 'true'
      TZ: Europe/Berlin
#     SPRING_PROFILES_ACTIVE: dev
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    depends_on:
      - crr-ehrbase


secrets:
  dic-fhir-postgres_password:
    file: ./dic/fhir/db/conf/postgres_password
  dic-bpe-postgres_password:
    file: ./dic/bpe/db/conf/postgres_password
  gth-fhir-postgres_password:
    file: ./gth/fhir/db/conf/postgres_password
  gth-bpe-postgres_password:
    file: ./gth/bpe/db/conf/postgres_password
  crr-fhir-postgres_password:
    file: ./crr/fhir/db/conf/postgres_password
  crr-bpe-postgres_password:
    file: ./crr/bpe/db/conf/postgres_password


networks:
  internet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24

  dic-fhir-frontend:
  dic-fhir-backend:
  dic-bpe-frontend:
  dic-bpe-backend:
  gth-fhir-frontend:
  gth-fhir-backend:
  gth-bpe-frontend:
  gth-bpe-backend:
  crr-fhir-frontend:
  crr-fhir-backend:
  crr-bpe-frontend:
  crr-bpe-backend:
  crr-ehrbase-network:


volumes:
  dic-fhir-db-data:
    name: dic-fhir-db-data
  dic-bpe-db-data:
    name: dic-bpe-db-data
  gth-fhir-db-data:
    name: gth-fhir-db-data
  gth-bpe-db-data:
    name: gth-bpe-db-data
  crr-fhir-db-data:
    name: crr-fhir-db-data
  crr-bpe-db-data:
    name: crr-bpe-db-data
